# Workflow to add fills to GDS
name: Add fill to gds
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag_version:
        description: 'Version to process'
        default: 'v1'
        required: true
        type: string

jobs:
  add_fills:
    runs-on: ubuntu-latest
    # required to checkout in container
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'

    container:
      image: hpretl/iic-osic-tools:chipathon26
      options: --user 0
      env:
        ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'
        DOWNLOADS_PATH: './downloads'

    defaults:
      run:
        shell: bash
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Update the DRC deck and scripts
      run: |
        bash ./setup/patch-drc.sh
        bash ./setup/patch-scripts.sh

    # Runs a single command using the runners shell
    - name: Setting the version
      run: echo "Hello ${{ inputs.tag_version }}"

    # Step: Download only matching files using rclone
    - name: Download specific files from Google Drive
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        # Replace with your actual Google Drive Folder ID
        DRIVE_FOLDER_ID: "1i40jdYf53io3pKjWkeNjxL7VZ800jq5o"
      run: |
        # 1. Install rclone
        sudo apt-get update && sudo apt-get install -y rclone

        # 2. Write service account secret to a temporary JSON file
        echo "$GCP_SA_KEY" > /tmp/sa.json

        # 3. Download using rclone with wildcard pattern filtering
        # Pattern breakdown:
        rclone copy \
          --drive-service-account-file /tmp/sa.json \
          --drive-root-folder-id "$DRIVE_FOLDER_ID" \
          --include "SSCS_2026_0[1-4]_${{ inputs.tag_version }}.tar.xz" \
          :drive: $DOWNLOADS_PATH

        # 4. Clean up service account key file
        rm /tmp/sa.json


    # Step: Check the list of files
    - name: Check list of files
      run: |
        FILE_PATH=$DOWNLOADS_PATH
        
        if [ ! -s "$FILE_PATH" ]; then
          echo "Error: File '$FILE_PATH' does not exist or is empty."
          exit 1
        fi

        ls $DOWNLOADS_PATH
    
        echo "File exists and is not empty."
